// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJAXv-WyUXjCwdY1UHFaraCohKDqV4oM',
    appId: '1:613393439991:web:33f2f87e703c3c61f287f2',
    messagingSenderId: '613393439991',
    projectId: 'cricketworld-c77b4',
    authDomain: 'cricketworld-c77b4.firebaseapp.com',
    storageBucket: 'cricketworld-c77b4.appspot.com',
    measurementId: 'G-F2V42GJMZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNevw1o10Z5lDSjRkrSu-5fsolzdcACLg',
    appId: '1:613393439991:android:1c0e93f32e833019f287f2',
    messagingSenderId: '613393439991',
    projectId: 'cricketworld-c77b4',
    storageBucket: 'cricketworld-c77b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmuw2XEaEHnD4qYY_3nv8dPFcw5w5ZM0o',
    appId: '1:613393439991:ios:e79a678ff2b595ebf287f2',
    messagingSenderId: '613393439991',
    projectId: 'cricketworld-c77b4',
    storageBucket: 'cricketworld-c77b4.appspot.com',
    iosBundleId: 'com.example.cricketWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmuw2XEaEHnD4qYY_3nv8dPFcw5w5ZM0o',
    appId: '1:613393439991:ios:e79a678ff2b595ebf287f2',
    messagingSenderId: '613393439991',
    projectId: 'cricketworld-c77b4',
    storageBucket: 'cricketworld-c77b4.appspot.com',
    iosBundleId: 'com.example.cricketWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZJAXv-WyUXjCwdY1UHFaraCohKDqV4oM',
    appId: '1:613393439991:web:bc902ec824b469a3f287f2',
    messagingSenderId: '613393439991',
    projectId: 'cricketworld-c77b4',
    authDomain: 'cricketworld-c77b4.firebaseapp.com',
    storageBucket: 'cricketworld-c77b4.appspot.com',
    measurementId: 'G-3G9FY4XDYH',
  );
}
